version: '3'

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: zitrus
    ports:
      - 3306:3306
  app:
    image: maven:3.8.4-openjdk-11
    depends_on:
      - mysql
    entrypoint: mvn -f /home/app spring-boot:run
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./:/home/app